### ISSUE TITLE
Quote swap on json Liquid variable

### ISSUE THREAD

**Issue by charlespwd** [Shopify/prettier-plugin-liquid#168]
**Describe the bug**
Quote swap on Liquid output is unsafe.

**Unformatted source**
```liquid
<div data-json='{{ json_object }}'></div>
```

**Expected output**
```liquid
<div data-json='{{ json_object }}'></div>
```

**Actual output**
```liquid
<div data-json="{{ json_object }}"></div>
```

**Additional context**
The quote swap breaks the HTML parsing. I think we have to revert the quote swap if there's Liquid in the attribute. No way to know.

**Comment by ChrisCrossCrash** [comment]
I'm seeing this a lot on the project I'm working on. Confusingly, an earlier developer on the project used lots of code like this:

```html
<div
  data-something={{ someStringVar | json }}
></div>
```

So that way, the template would be evaluated like this:

```html
<div
  data-something="someValue"
></div>
```

When I run formatting on the document, it wraps `{{ someStringVar | json }}` in single quotes:

```html
<div
  data-something='{{ someStringVar | json }}'
></div>
```

Which causes `someValue` to be wrapped in quotes:

```html
<div
  data-something="\"someValue\""
></div>
```

**Comment by charlespwd** [comment]
The actual solution for this is to not quote swap _ever_. But I think that's a bit too picky for an edge-case. IMO JSON shouldn't be in a data-attribute but rather in a <script type="application/json"></script> tag instead. It makes for nicer to look at HTML too.

```liquid
<div data-json-id='json-id-1'></div>
<script id="json-id-1" type="application/json">
  {{ json_object }}
</script>
<script>
  // example access
  const json = JSON.parse(document.getElementById('json-id-1'));
</script>
```
