### ISSUE TITLE
Add support for `.html` files

### ISSUE THREAD

**Issue by khoait** [Shopify/prettier-plugin-liquid#182]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the plugin for `.html` containing liquid. and I get the error 

```
Extension 'Shopify Liquid' is configured as formatted but it cannot format 'HTML'-files
```

It would be nice if the plugin can support `.html` in addition to `.liquid` files.

**Describe the solution you'd like**

the plugin can format `.html` files in the same manner as `.liquid` files.

**Describe alternatives you've considered**
N/A

**Checklist** 
- [x] I have checked and made sure that the proposal adheres to this plugin's [principles](https://github.com/Shopify/prettier-plugin-liquid/blob/main/docs/principles/index.md)

**Additional context**
I'm using VS Code on Windows.

**Comment by aurelienbobenrieth** [comment]
Have you tried changing your VS Code user settings with:
```json
  "[html]": {
    "editor.defaultFormatter": "Shopify.theme-check-vscode",
  }
```

Didn't try it myself though, just an idea.

**Comment by johnpuddephatt** [comment]
I was able to do this by adding the following to my .prettierrc.json:

````
{
  "plugins": ["@shopify/prettier-plugin-liquid"],
  "overrides": [
    {
      "files": "*.html",
      "options": {
        "parser": "liquid-html"
      }
    }
  ]
}
````
