### ISSUE TITLE
Not respecting prettier config

### ISSUE THREAD

**Issue by james-prado** [Shopify/prettier-plugin-liquid#192]
**Describe the bug**
The `Shopify.theme-check-vscode` formatter indents with spaces even when `"prettier.useTabs": true` specified.

**Unformatted source**
```liquid
{%- assign foo = 'foo' -%}

<div
  class='test'
  {% if foo != blank %}
    id='{{ foo }}'
  {% endif %}
></div>

```

**Expected output**
```liquid
{%- assign foo = 'foo' -%}

<div
	class='test'
	{% if foo != blank %}
		id='{{ foo }}'
	{% endif %}
></div>

```

**Actual output**
```liquid
{%- assign foo = 'foo' -%}

<div
  class='test'
  {% if foo != blank %}
    id='{{ foo }}'
  {% endif %}
></div>

```

**Debugging information**
 - OS: Mac
 - Version: [Shopify Liquid](https://marketplace.visualstudio.com/items?itemName=Shopify.theme-check-vscode) (VSCode marketplace) `v1.10.0`

**Comment by charlespwd** [comment]
We have integration tests that says otherwise. Mind sharing your config? 

https://github.com/Shopify/prettier-plugin-liquid/blob/main/test/config-use-tabs/fixed.liquid#L8-L14

**Comment by charlespwd** [comment]
Here's a PR that shows your PR works too. So something is up with how your config is being read.

https://github.com/Shopify/prettier-plugin-liquid/pull/193

**Comment by anders-christiansen** [comment]
I have the same issue.

I have created a .prettierrc.json file with printWidth: 800, which does not work in liquid files.

`{
  "printWidth": 800
}
`

my settings.json file looks like this:

```
{
  "editor.largeFileOptimizations": false,
  "workbench.iconTheme": "material-icon-theme",
  "tabnine.experimentalAutoImports": true,
  "editor.inlineSuggest.enabled": true,
  "github.copilot.enable": {
    "*": true,
    "plaintext": false,
    "markdown": false,
    "scminput": false,
    "yaml": true,
    "xml": true,
    "javascript": true,
    "typescript": true
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.formatOnSave": true,
  "cssPeek.peekFromLanguages": [
    "html",
    "django-html",
    "laravel-blade",
    "razor",
    "vue",
    "blade",
    "pug",
    "jade",
    "handlebars",
    "php",
    "twig",
    "md",
    "nunjucks",
    "javascript",
    "javascriptreact",
    "erb",
    "typescript",
    "typescriptreact",
    "HTML (Eex)",
    "html-eex",
    "ejs",
    "liquid"
  ],
  "editor.unicodeHighlight.nonBasicASCII": false,
  "editor.unicodeHighlight.invisibleCharacters": false,
  "editor.linkedEditing": true,
  "editor.fontSize": 14,
  "workbench.colorTheme": "Dracula",
  "tailwindCSS.includeLanguages": {
    "html": "liquid"
  },
  "editor.detectIndentation": false,
  "prettier.tabWidth": 2,
  "themeCheck.checkOnChange": false,
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[liquid]": {
    "editor.defaultFormatter": "Shopify.theme-check-vscode"
  },
  "themeCheck.checkOnOpen": false,
  "files.autoSave": "onFocusChange",
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "npm.keybindingsChangedWarningShown": true,
  "editor.tabSize": 2,
  "shopifyLiquid.shopifyCLIPath": "",
  "shopifyLiquid.disableWindowsWarning": false,
  
}
```


If i change the editor.defaultFormatter from Shopify.theme-check-vscode to esbenp.prettier-vscode everything works as expected. But the Shopify.theme-check-vscode is not working

**Comment by charlespwd** [comment]
Thing is... While we don't "watch for changes." It seems to be working for me?


https://github.com/Shopify/prettier-plugin-liquid/assets/4990691/b07128d9-0600-40cb-9df3-f06dd061f648

**Comment by james-prado** [comment]
This is weird 😕


https://github.com/Shopify/prettier-plugin-liquid/assets/13836920/0df93866-15db-4bb4-8429-2cf42493cbae


Could it maybe be that some globally installed npm packages are interfering? I'm not really using anything unusual, just some basic prettier plugins.

![CleanShot 2023-06-29 at 14 57 15@2x](https://github.com/Shopify/prettier-plugin-liquid/assets/13836920/4515e72c-e50e-4a7c-86c8-f838ee656d13)

**Comment by charlespwd** [comment]
The shape of the icons on the sidebar tells me you're using another VS Code extension for Liquid. Are you sure that's not conflicting with Shopify.theme-check-vscode?

https://marketplace.visualstudio.com/items?itemName=Shopify.theme-check-vscode

Note that we respect the config files as recognized by the prettier CLI. So cosmiconfig .prettierrc/.json/etc is what we'll uphold.

And like I said, you do need to reload the window. It appears that we cache the result of the config internally.

**Comment by james-prado** [comment]
I'm confident that the icons aren't causing issues. I use an extension called [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) that lets me customize the file icons.

Just to be sure I removed all my vscode settings, disabled all extensions except Prettier and Shopify Liquid, uninstalled all my global npm packages, and made sure to reload vscode. Unfortunately the issue persists. 

https://github.com/Shopify/prettier-plugin-liquid/assets/13836920/dad4a1e9-759e-41e7-bf8f-d31ff3cd6cd0
