### ISSUE TITLE
Empty html attribute value throws error with Node v14

### ISSUE THREAD

**Issue by mattvague** [Shopify/prettier-plugin-liquid#204]
**Describe the bug**
When using this plugin with Node v14, an html attribute with an empty value e.g. `<div class="">` will throw an error since `Array.prototype.at` is used [here](https://github.com/Shopify/prettier-plugin-liquid/blob/main/src/parser/stage-2-ast.ts#L980-L981) in the parser but is [not supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility) until (I believe) Node v.16.6.0. 

<img width="513" alt="image" src="https://github.com/Shopify/prettier-plugin-liquid/assets/64985/19ed6b80-8f0d-40b7-9cf7-b113b4d030a0">

Not sure what the minimum node version you're looking to support is, but I'm happy to fix it and submit a PR if this is deemed worth it

**Debugging information**
 - OS: Mac
 - Version 1.2.2

**Comment by charlespwd** [comment]
Hi Matt. Node v14 is end of life and we will not support it. I encourage you to update to at least 18, 16 is going end of life in a couple months.

https://nodejs.dev/en/about/releases/
