### ISSUE TITLE
Prettier v3 doesn't run on .liquid files unless specified

### ISSUE THREAD

**Issue by andershagbard** [Shopify/prettier-plugin-liquid#208]
**Describe the bug**
In Prettier v2, it was possible to just use `prettier .`, and it would run on on all files, including `.liquid` files.
In Prettier v3, you have to use `prettier --write '**/*.liquid'` to make it run on `.liquid` files.

**Debugging information**
 - MacOS
 - prettier-plugin-liquid v.1.2.2
 - prettier 3.0.3

**Comment by charlespwd** [comment]
Yep that's a v3 breaking change from prettier unfortunately. I'm not happy with how they communicated it.

Try adding this to your .prettierrc.json

```
{
  "plugins": ["@shopify/prettier-plugin-liquid"]
}
```

https://github.com/prettier/prettier/issues/15088

**Comment by andershagbard** [comment]
Seems like a bug in Prettier. I'll create a ticket.

> prettier . --write
> This command formats all files supported by Prettier in the current directory and its subdirectories.

https://prettier.io/docs/en/cli.html

**Comment by emilqva** [comment]
Just add this to settings.json in vscode:

```
{
"[liquid]": {
    "editor.defaultFormatter": "Shopify.theme-check-vscode",
    "editor.formatOnSave": true
  },
}
```

This will also enable format on save.

**Comment by Velkamhell97** [comment]
Any solution ?

**Comment by andershagbard** [comment]
> Any solution ?

Should be working now. Just update your packages
