### ISSUE TITLE
Avoid the final new line on snippets

### ISSUE THREAD

**Issue by bernier** [Shopify/prettier-plugin-liquid#220]
It doesn't seem possible to disable this feature

I tried

"files.insertFinalNewline": false
and
"insertFinalNewLine": false

within .prettierrc and the VS Code settings without success

**Comment by charlespwd** [comment]
Unfortunately, final new line has nothing to do with the plugin. Could be a [editorconfig](https://editorconfig.org/), could be editor setting, but I don't think that's a prettier plugin specific issue. It could be general prettier config, but we don't have control over that as far as I am aware.
