### ISSUE TITLE
YAML frontmatter support

### ISSUE THREAD

**Issue by Dexus** [Shopify/prettier-plugin-liquid#29]
**Describe the bug**
This plugin killing the frontmatter data of a template.

**Unformatted source**
```liquid
---
layout: false
permalink: /test-de.html
title: 'Test Layout'
translationKey: page-test-layout
locale: de
dir: ltr
---
<div>
<span>demo</span>
</div>
```

**Expected output**
```liquid
---
layout: false
permalink: /test-de.html
title: 'Test Layout'
translationKey: page-test-layout
locale: de
dir: ltr
---
<div>
  <span>demo</span>
</div>
```

**Actual output**
```liquid
--- layout: false permalink: /test-de.html title: 'Test Layout' translationKey: page-test-layout locale: de dir: ltr ---
<div>
  <span>demo</span>
</div>

```

**Debugging information**
 - Linux 
 - Version 0.1.4
 - `"@shopify/prettier-plugin-liquid": "^0.1.4",`

**Additional context**
Default prettier keeps the front-matter data, but this plugin is killing it.

**Comment by charlespwd** [comment]
Released just now :)
