### ISSUE TITLE
npm run format: Doesn't work

### ISSUE THREAD

**Issue by Efthymios-Papakostopoulos** [Shopify/prettier-plugin-liquid#51]
**I am getting the following error**

```Debugger attached.
[error] No files matching the pattern were found: "'**/*.liquid'".
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

Am I doing something wrong?

**Comment by charlespwd** [comment]
Can you include more information? Things I'd like to know to help you debug:

- Where does this output come from (terminal or editor)
- What OS you're using (macOS, linux, Windows?)
- If terminal, what's the command you're using (and in which folder?)
- If editor, is this a workspace issue?

The error you're seeing indicates that it can't find Liquid files from the place where the command is run. So there could be a number of reasons why this is happening, and the above info would help :)

**Comment by charlespwd** [comment]
Sorry, just to be clear, does the package.json live _next_ to the `.liquid` files or are the `.liquid` files in a subfolder?

(FYI) I'm starting to believe this is a Windows + glob issue. But gotta confirm first.

**Comment by charlespwd** [comment]
Gotcha, thanks that looks like an issue indeed. Will have to look into how prettier handles glob arguments on windows.

**Comment by charlespwd** [comment]
Hmm. So it looks like [all you need is double quotes](https://github.com/prettier/prettier/issues/4804#issuecomment-402476898).

So this:

```json
{
  "scripts": {
    "format": "prettier --write \"**/*.liquid\""
  }
}
```

LMK if that works, I'll update the docs :)

**Comment by Efthymios-Papakostopoulos** [comment]
As i can see they're


![image](https://user-images.githubusercontent.com/77063189/183493185-20bd2261-5fc3-4f2e-932c-77f5446c701b.png)

**Comment by charlespwd** [comment]
Aye aye ok I'll have to try this on my personal windows box. No idea why it would do that. 

Can you try the `--plugin <path>` option? Something like
```
"format": "prettier --plugin \"node_modules\@shopify\prettier-plugin-liquid\" \"**/*.liquid\""
```

**Comment by Efthymios-Papakostopoulos** [comment]
I will disappoint you but nop 


```npm ERR! code EJSONPARSE
npm ERR! path CENCORED
npm ERR! JSON.parse Unexpected token "@" (0x40) in JSON at position 172 while parsing near "...ugin \\\"node_modules\\@shopify\\prettier-pl..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.```

**Comment by charlespwd** [comment]
Durr. This is what happens when I write stuff in a textarea instead of my editor 😓 

I didn't escape the backslashes in the json command 🤦 

```json
{
  "format": "prettier --plugin \"node_modules\\@shopify\\prettier-plugin-liquid\" \"**/*.liquid\""
}
```

**Comment by charlespwd** [comment]
Ah ha! 🙌  Well that's the thing working!

What you're seeing there is a known prettier issue we can't fix:
https://github.com/Shopify/prettier-plugin-liquid/blob/main/KNOWN_ISSUES.md#liquid-that-cant-be-prettier

Basically, for prettier to work on your code, you can't have open html tags inside liquid tags without its closing end. 

e.g. can't have 
```liquid
{% if hi %}
  <div>not closed!
{% endif %}
{%if hi %}
  </div>
{%end %}
```
