### ISSUE TITLE
YAML frontmatter support for YAML that contains Liquid

### ISSUE THREAD

**Issue by LarsBodewig** [Shopify/prettier-plugin-liquid#57]
**Describe the bug**
Follow-up to #29: YAML maps break on formatting
This is an example from the eleventy docs: https://www.11ty.dev/docs/data-computed/#using-a-template-string

**Unformatted source**
```liquid
---
a: b
eleventyComputed: 
    c: "{{ d }}"
e: f
---
```

**Expected output**
Same as above

**Actual output**
```liquid
---
a: b
eleventyComputed: 
    c: "{{ d }}" e: f ---
```

**Debugging information**
 - OS Windows
 - Version 0.2.0

**Additional context**
- Tried to add `# prettier-ignore` or `<!-- prettier-ignore-start/end -->` with no luck (it would actually break comments like 
```liquid
e: f #
comment ---
```
- Briefly tried a YAML list of maps which also breaks:
```liquid
---
a: b
eleventyComputed: 
- c: "{{ d }}" e: f ---
```

**Comment by charlespwd** [comment]
Once again, I'm getting bit by "Oh people don't do X, this is going to work if I take this shortcut here." and being wrong :upside_down_smile:.

Note: I thought(?) that 11ty was Liquid + Markdown, and this plugin (as per README) is for Liquid + HTML, so there might be a _lot_ more issues than broken YAML. It's not on our roadmap to support Liquid + Markdown (but would welcome contributions!)

Nevertheless, I'll try to include something more robust as a fix for frontmatter only (assuming the rest of the body is HTML, and not markdown).

**Comment by LarsBodewig** [comment]
> Note: I thought(?) that 11ty was Liquid + Markdown, and this plugin (as per README) is for Liquid + HTML

As far as I understand, 11ty supports both, the docs have usage examples for both atleast: https://www.11ty.dev/docs/pagination/#aliasing-to-a-different-variable
Personally I use Liquid + HTML, I don't know if it's that common though.

**Comment by LarsBodewig** [comment]
Awesome, nice work!
