### ISSUE TITLE
Prettier `{% javascript %}` and `<script>` tags

### ISSUE THREAD

**Issue by charlespwd** [Shopify/prettier-plugin-liquid#7]
While we're not going to format Liquid-in-JS, we can probably embed the javascript prettier plugin for script tags and `{% javascript %}` tags _that do not contain Liquid code_.

## Problem

We want to use the prettier's JavaScript formatter inside script tags that don't contain liquid.

Input:
```liquid
<script>
async function main() {
const sleep=(ms)=>new Promise(resolve => setTimeout(resolve, ms))
await sleep(30); console.log('belated hello world')}
</script>
```

Expected output:
```liquid
<script>
  async function main() {
    const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));
    await sleep(30);
    console.log('belated hello world');
  }
</script>
```

**Comment by jullite** [comment]
hi, would you tell me when this job will be finished? It's very nice to here that liquid prettier plugin has published for a while, but js-in-liquid a common use for many developers. We do really need this function.

**Comment by Christoph-AK** [comment]
Would be awesome if this would respect an existing .prettierrc to format the JS inside so the style is consistent with any .js-assets.

**Comment by charlespwd** [comment]
> Would be awesome if this would respect an existing .prettierrc to format the JS inside so the style is consistent with any .js-assets.

Unfortunately, an upstream issue prevents us from doing it:
https://github.com/prettier/prettier/issues/5378
