### ISSUE TITLE
Extra whitespace added before closing tag

### ISSUE THREAD

**Issue by jozef-mokry** [Shopify/prettier-plugin-liquid#93]
**Describe the bug**
The prettier-plugin-liquid adds an unnecessary whitespace just before some closing `%}` liquid tags. When I ran prettier on the same file N times, it adds N spaces before the closing tag.

In this example, the closing `%}` of the if statement will get an extra space before it each time it is prettier-ified.
**Unformatted source**
```liquid
{% if page.['Foo Bar'] %}
  Hello
{% endif %}
```

**Expected output**
same as input
```liquid
{% if page.['Foo Bar'] %}
  Hello
{% endif %}
```

**Actual output**
Notice the extra whitespace added after `]`
This is the output of `npx prettier --parser liquid-html test.html`
```liquid
{% if page.['Foo Bar']  %}
  Hello
{% endif %}
```

**Debugging information**
 - OS MacOS
 - Version 12.3.1

**Additional context**
```
$ cat package.json
{
  "devDependencies": {
    "@shopify/prettier-plugin-liquid": "^0.3.0",
    "browser-sync": "^2.27.9",
    "prettier": "^2.7.1"
  }
}

$ cat .prettierrc
{
  "tabWidth": 2,
  "semi": true,
  "singleQuote": false,
  "overrides": [
    {
      "files": "*.html",
      "options": {
        "parser": "liquid-html"
      }
    }
  ]
}
```

**Comment by charlespwd** [comment]
Should be fixed in v0.3.1 :pray:
