### ISSUE TITLE
Support Typescript Module Declaration

### ISSUE THREAD

**Issue by albchu** [Shopify/prettier-plugin-liquid#97]
**Describe the bug**
Receiving a type declaration error when I use this package in a typescript component. It would be sweet if we could add "typing" to the package file to avoid this.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/5607117/188166766-ed5d3e17-b549-4840-873a-36a0329d472c.png">

Currently jankily suppressing this with 
```typescript
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import liquidPlugin from '@shopify/prettier-plugin-liquid/standalone';
```

**Additional context**
Using  "version": "0.3.1" to build prettier formatting into the code editor.

**Comment by charlespwd** [comment]
Fixed in https://github.com/Shopify/prettier-plugin-liquid/commit/1af0619948b5f1fceee0652f303a7a4a793a225c
